"""empty message

Revision ID: aff6833d849a
Revises: 
Create Date: 2017-05-12 23:52:53.895000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aff6833d849a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('itineraryDate', sa.Date(), nullable=True))
    op.add_column('itineraries', sa.Column('itineraryTime', sa.Time(), nullable=True))
    op.alter_column('itineraries', 'locationTypeID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('itineraries', 'itineraryTimeTo')
    op.drop_column('itineraries', 'itineraryDateFrom')
    op.drop_column('itineraries', 'itineraryTimeFrom')
    op.drop_column('itineraries', 'itineraryDateTo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('itineraryDateTo', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('itineraries', sa.Column('itineraryTimeFrom', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('itineraries', sa.Column('itineraryDateFrom', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('itineraries', sa.Column('itineraryTimeTo', postgresql.TIME(), autoincrement=False, nullable=True))
    op.alter_column('itineraries', 'locationTypeID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('itineraries', 'itineraryTime')
    op.drop_column('itineraries', 'itineraryDate')
    # ### end Alembic commands ###
