"""empty message

Revision ID: bc584c7196f2
Revises: 
Create Date: 2017-05-12 19:22:46.505000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc584c7196f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('itineraryLocation', sa.String(length=80), nullable=True))
    op.add_column('itineraries', sa.Column('locationTypeID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'itineraries', 'itinerarylocationtype', ['locationTypeID'], ['locationTypeID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itineraries', type_='foreignkey')
    op.drop_column('itineraries', 'locationTypeID')
    op.drop_column('itineraries', 'itineraryLocation')
    # ### end Alembic commands ###
